// 300 styrkeøvelser for Styrkestudio 3475 Kraftverket
// group: bryst | rygg | skuldre | bicep | tricep | underarm | quad | ham | glute | legger | mage | helkropp
// equipment: stang | manual | maskin | kabel | kettlebell | kroppsvekt | smith | benk | hjul | bånd
// level: begynner | middels | erfaren

window.EXERCISES = [
  // ── BRYST (35) ──
  { id:"b1",  name:"Benkpress med stang",          eng:"Barbell Bench Press",         group:"bryst",  equipment:"stang",     level:"middels",   sets:"4 x 6-8",   desc:"Klassisk hovedøvelse for bryst. Senk stangen kontrollert til brystet, press eksplosivt opp." },
  { id:"b2",  name:"Skrå benkpress (incline)",     eng:"Incline Bench Press",         group:"bryst",  equipment:"stang",     level:"middels",   sets:"4 x 8-10",  desc:"Benk satt på 30-45 grader for å treffe øvre brystfibre." },
  { id:"b3",  name:"Dekline benkpress",            eng:"Decline Bench Press",         group:"bryst",  equipment:"stang",     level:"middels",   sets:"3 x 8-12",  desc:"Negativ vinkel for nedre del av brystet." },
  { id:"b4",  name:"Benkpress med manualer",       eng:"Dumbbell Bench Press",        group:"bryst",  equipment:"manual",    level:"begynner",  sets:"4 x 8-12",  desc:"Større bevegelsesutslag enn med stang, jevn aktivering." },
  { id:"b5",  name:"Skrå manualpress",             eng:"Incline Dumbbell Press",      group:"bryst",  equipment:"manual",    level:"middels",   sets:"3 x 10",    desc:"Øvre bryst med manualer for full ROM." },
  { id:"b6",  name:"Manualflyes flat",             eng:"Dumbbell Fly",                group:"bryst",  equipment:"manual",    level:"begynner",  sets:"3 x 12",    desc:"Isolasjonsøvelse - åpne armer som vinger, hold lett bøy i albuen." },
  { id:"b7",  name:"Skrå manualflyes",             eng:"Incline Dumbbell Fly",        group:"bryst",  equipment:"manual",    level:"middels",   sets:"3 x 12",    desc:"Isolasjon av øvre bryst." },
  { id:"b8",  name:"Cable crossover (høy)",        eng:"High-to-Low Cable Crossover", group:"bryst",  equipment:"kabel",     level:"begynner",  sets:"3 x 12-15", desc:"Trekk kablene ned-og-inn for nedre bryst." },
  { id:"b9",  name:"Cable crossover (lav)",        eng:"Low-to-High Cable Crossover", group:"bryst",  equipment:"kabel",     level:"begynner",  sets:"3 x 12-15", desc:"Trekk opp-og-inn for øvre bryst." },
  { id:"b10", name:"Cable fly midten",             eng:"Mid Cable Fly",               group:"bryst",  equipment:"kabel",     level:"begynner",  sets:"3 x 12-15", desc:"Klassisk crossover på brysthøyde." },
  { id:"b11", name:"Pec deck (machine fly)",       eng:"Pec Deck Machine",            group:"bryst",  equipment:"maskin",    level:"begynner",  sets:"3 x 12",    desc:"Sittende isolasjon med klem mot midten." },
  { id:"b12", name:"Brystpress maskin",            eng:"Chest Press Machine",         group:"bryst",  equipment:"maskin",    level:"begynner",  sets:"3 x 10-12", desc:"Trygg press for nybegynnere." },
  { id:"b13", name:"Brystpress maskin (skrå)",     eng:"Incline Chest Press Machine", group:"bryst",  equipment:"maskin",    level:"begynner",  sets:"3 x 10-12", desc:"Skrå variant for øvre bryst." },
  { id:"b14", name:"Smith maskin benkpress",       eng:"Smith Machine Bench Press",   group:"bryst",  equipment:"smith",     level:"begynner",  sets:"4 x 8-10",  desc:"Guidet stang - god for kontroll og høyere reps." },
  { id:"b15", name:"Smith skrå benkpress",         eng:"Smith Incline Press",         group:"bryst",  equipment:"smith",     level:"begynner",  sets:"3 x 10",    desc:"Stabil skrå variant." },
  { id:"b16", name:"Pushup",                        eng:"Push-up",                     group:"bryst",  equipment:"kroppsvekt",level:"begynner",  sets:"3 x maks",  desc:"Klassisk armhevings." },
  { id:"b17", name:"Skrå pushup (fra benk)",       eng:"Incline Push-up",             group:"bryst",  equipment:"kroppsvekt",level:"begynner",  sets:"3 x 15",    desc:"Lettere variant - hender på benk." },
  { id:"b18", name:"Dekline pushup",                eng:"Decline Push-up",             group:"bryst",  equipment:"kroppsvekt",level:"middels",   sets:"3 x 12",    desc:"Føttene hevet - mer øvre bryst." },
  { id:"b19", name:"Diamond pushup",                eng:"Diamond Push-up",             group:"bryst",  equipment:"kroppsvekt",level:"middels",   sets:"3 x 10",    desc:"Hendene tett - mer tricep." },
  { id:"b20", name:"Plyometric pushup",             eng:"Plyo Push-up",                group:"bryst",  equipment:"kroppsvekt",level:"erfaren",   sets:"3 x 8",     desc:"Eksplosiv pushup med klapp." },
  { id:"b21", name:"Brystdips",                     eng:"Chest Dips",                  group:"bryst",  equipment:"kroppsvekt",level:"middels",   sets:"3 x 8-12",  desc:"Lent framover for å aktivere bryst." },
  { id:"b22", name:"Dips med vest",                 eng:"Weighted Dips",               group:"bryst",  equipment:"kroppsvekt",level:"erfaren",   sets:"4 x 6-8",   desc:"Tilleggsvekt for progresjon." },
  { id:"b23", name:"Floor press (gulvpress)",      eng:"Floor Press",                 group:"bryst",  equipment:"stang",     level:"middels",   sets:"3 x 6-8",   desc:"Ligg på gulv - korter ROM, sparer skuldre." },
  { id:"b24", name:"Manualpullover",                eng:"Dumbbell Pullover",           group:"bryst",  equipment:"manual",    level:"middels",   sets:"3 x 12",    desc:"Strekk bryst og lat - skap volum." },
  { id:"b25", name:"Larsen press",                  eng:"Larsen Press",                group:"bryst",  equipment:"stang",     level:"erfaren",   sets:"3 x 8",     desc:"Benkpress med føttene oppe - utfordrer stabilitet." },
  { id:"b26", name:"Spoto press",                   eng:"Spoto Press",                 group:"bryst",  equipment:"stang",     level:"erfaren",   sets:"4 x 5",     desc:"Pause 2cm over brystet - bryt momentum." },
  { id:"b27", name:"Close-grip benkpress",          eng:"Close-Grip Bench Press",      group:"bryst",  equipment:"stang",     level:"middels",   sets:"3 x 8",     desc:"Smalt grep - bryst + tricep." },
  { id:"b28", name:"Wide-grip benkpress",           eng:"Wide-Grip Bench Press",       group:"bryst",  equipment:"stang",     level:"middels",   sets:"3 x 8",     desc:"Bredt grep - mer bryst, mindre tricep." },
  { id:"b29", name:"Svebar pullover",               eng:"EZ-Bar Pullover",             group:"bryst",  equipment:"stang",     level:"middels",   sets:"3 x 10",    desc:"Pullover med svebar." },
  { id:"b30", name:"Maskin pec fly",                eng:"Machine Chest Fly",           group:"bryst",  equipment:"maskin",    level:"begynner",  sets:"3 x 12-15", desc:"Isolasjon av bryst på maskin." },
  { id:"b31", name:"Land mine press",               eng:"Landmine Press",              group:"bryst",  equipment:"stang",     level:"middels",   sets:"3 x 10",    desc:"Stang i hjørne, press i diagonal." },
  { id:"b32", name:"Svisseball pushup",             eng:"Swiss Ball Push-up",          group:"bryst",  equipment:"kroppsvekt",level:"middels",   sets:"3 x 12",    desc:"Pushup med føtter på ball - kjernekrav." },
  { id:"b33", name:"Manualpress på ball",           eng:"Dumbbell Press on Ball",      group:"bryst",  equipment:"manual",    level:"middels",   sets:"3 x 10",    desc:"Press på svissball - stabilisering." },
  { id:"b34", name:"Squeeze press",                 eng:"Dumbbell Squeeze Press",      group:"bryst",  equipment:"manual",    level:"begynner",  sets:"3 x 12",    desc:"Press manualer tett sammen hele tiden." },
  { id:"b35", name:"Svebar svensk press",           eng:"Swedish Press",               group:"bryst",  equipment:"stang",     level:"erfaren",   sets:"3 x 8",     desc:"Press med brede albuer over bryst." },

  // ── RYGG (35) ──
  { id:"r1",  name:"Markløft",                      eng:"Conventional Deadlift",       group:"rygg",   equipment:"stang",     level:"middels",   sets:"4 x 5",     desc:"Helkroppsøvelse - løft stangen fra gulv til hofte." },
  { id:"r2",  name:"Romersk markløft",              eng:"Romanian Deadlift (RDL)",     group:"rygg",   equipment:"stang",     level:"middels",   sets:"4 x 8",     desc:"Fokus på hamstrings og rygg - bøy i hofte, lett bøy i kne." },
  { id:"r3",  name:"Sumo markløft",                 eng:"Sumo Deadlift",               group:"rygg",   equipment:"stang",     level:"middels",   sets:"4 x 5",     desc:"Bredt fotstilling - mer hofte/glute." },
  { id:"r4",  name:"Stiff-leg deadlift",            eng:"Stiff-Leg Deadlift",          group:"rygg",   equipment:"stang",     level:"middels",   sets:"3 x 8",     desc:"Strake bein - maks belastning på baksiden." },
  { id:"r5",  name:"Trap bar deadlift",             eng:"Trap Bar Deadlift",           group:"rygg",   equipment:"stang",     level:"begynner",  sets:"4 x 6",     desc:"Sekskantet stang - vennligere for rygg." },
  { id:"r6",  name:"Pull-up (kroppsvekt)",          eng:"Pull-up",                     group:"rygg",   equipment:"kroppsvekt",level:"middels",   sets:"4 x maks",  desc:"Overhåndsgrep - bredt og smalt etter mål." },
  { id:"r7",  name:"Chin-up",                       eng:"Chin-up",                     group:"rygg",   equipment:"kroppsvekt",level:"middels",   sets:"4 x maks",  desc:"Undergrep - mer bicep og lat." },
  { id:"r8",  name:"Neutral grip pull-up",          eng:"Neutral Grip Pull-up",        group:"rygg",   equipment:"kroppsvekt",level:"middels",   sets:"3 x 8",     desc:"Hammer-grep - skuldervennlig." },
  { id:"r9",  name:"Weighted pull-up",              eng:"Weighted Pull-up",            group:"rygg",   equipment:"kroppsvekt",level:"erfaren",   sets:"4 x 5",     desc:"Pull-up med vest eller belte." },
  { id:"r10", name:"Lat pulldown (bredt grep)",     eng:"Wide-Grip Lat Pulldown",      group:"rygg",   equipment:"kabel",     level:"begynner",  sets:"4 x 10",    desc:"Klassisk lat-isolasjon." },
  { id:"r11", name:"Lat pulldown (smalt grep)",     eng:"Close-Grip Lat Pulldown",     group:"rygg",   equipment:"kabel",     level:"begynner",  sets:"3 x 12",    desc:"Smalt grep - mer bicep og indre rygg." },
  { id:"r12", name:"Reverse lat pulldown",          eng:"Reverse-Grip Lat Pulldown",   group:"rygg",   equipment:"kabel",     level:"middels",   sets:"3 x 10",    desc:"Undergrep - mer nedre lat." },
  { id:"r13", name:"Sittende roing kabel",          eng:"Seated Cable Row",            group:"rygg",   equipment:"kabel",     level:"begynner",  sets:"4 x 10",    desc:"Trekk håndtak mot magen - hold rygg rett." },
  { id:"r14", name:"Sittende roing bredt grep",     eng:"Wide-Grip Seated Row",        group:"rygg",   equipment:"kabel",     level:"middels",   sets:"3 x 12",    desc:"Bredt stang-grep for ytre rygg." },
  { id:"r15", name:"Stang roing (bent over)",       eng:"Bent-Over Barbell Row",       group:"rygg",   equipment:"stang",     level:"middels",   sets:"4 x 8",     desc:"Bøyd over, trekk stangen mot magen." },
  { id:"r16", name:"Pendlay row",                   eng:"Pendlay Row",                 group:"rygg",   equipment:"stang",     level:"erfaren",   sets:"4 x 5",     desc:"Eksplosiv row fra gulv hver rep." },
  { id:"r17", name:"Yates row (undergrep)",         eng:"Yates Row",                   group:"rygg",   equipment:"stang",     level:"middels",   sets:"3 x 8",     desc:"Mer oppreist undergrep-row." },
  { id:"r18", name:"T-bar row",                     eng:"T-Bar Row",                   group:"rygg",   equipment:"stang",     level:"middels",   sets:"3 x 10",    desc:"Stang i landmine - tjukk midtre rygg." },
  { id:"r19", name:"Manual one-arm row",            eng:"Single-Arm Dumbbell Row",     group:"rygg",   equipment:"manual",    level:"begynner",  sets:"3 x 10",    desc:"Kne og hånd på benk - row manual." },
  { id:"r20", name:"Chest-supported row (benk)",    eng:"Chest-Supported Row",         group:"rygg",   equipment:"manual",    level:"begynner",  sets:"3 x 12",    desc:"Ligg framover på skrå benk - fjern juks." },
  { id:"r21", name:"Maskin lat pulldown",           eng:"Lat Pulldown Machine",        group:"rygg",   equipment:"maskin",    level:"begynner",  sets:"3 x 10",    desc:"Sittende maskinvariant." },
  { id:"r22", name:"Maskin row",                    eng:"Machine Row",                 group:"rygg",   equipment:"maskin",    level:"begynner",  sets:"3 x 12",    desc:"Brystpute - trekk håndtak." },
  { id:"r23", name:"Cable face pull",               eng:"Face Pull",                   group:"rygg",   equipment:"kabel",     level:"begynner",  sets:"3 x 15",    desc:"Trekk rep mot ansiktet - bakre delt og rotator." },
  { id:"r24", name:"Cable straight-arm pulldown",   eng:"Straight-Arm Pulldown",       group:"rygg",   equipment:"kabel",     level:"middels",   sets:"3 x 12",    desc:"Strake armer trekker rett ned - isolerer lat." },
  { id:"r25", name:"Inverted row",                  eng:"Inverted Row",                group:"rygg",   equipment:"kroppsvekt",level:"begynner",  sets:"3 x 12",    desc:"Lig under stang, trekk kroppen opp." },
  { id:"r26", name:"Meadow row",                    eng:"Meadow Row",                  group:"rygg",   equipment:"stang",     level:"erfaren",   sets:"3 x 10",    desc:"Single-arm landmine row." },
  { id:"r27", name:"Seal row",                      eng:"Seal Row",                    group:"rygg",   equipment:"stang",     level:"erfaren",   sets:"3 x 8",     desc:"Ligg flat på benk - strict row." },
  { id:"r28", name:"Helms row",                     eng:"Helms Row",                   group:"rygg",   equipment:"manual",    level:"middels",   sets:"3 x 10",    desc:"Stå-row med bredt fotstilling." },
  { id:"r29", name:"Kroc row",                      eng:"Kroc Row",                    group:"rygg",   equipment:"manual",    level:"erfaren",   sets:"3 x 20",    desc:"Tung manual - høy rep og momentum." },
  { id:"r30", name:"Trap-3 raise",                  eng:"Trap-3 Raise",                group:"rygg",   equipment:"manual",    level:"middels",   sets:"3 x 12",    desc:"Skrå benk på 30 grader - hev manual i Y." },
  { id:"r31", name:"Reverse hyperextension",        eng:"Reverse Hyper",               group:"rygg",   equipment:"maskin",    level:"middels",   sets:"3 x 12",    desc:"Korsrygg og glute - hev bena bakover." },
  { id:"r32", name:"Hyperextension (rygg-ekst)",    eng:"Back Extension",              group:"rygg",   equipment:"maskin",    level:"begynner",  sets:"3 x 15",    desc:"Klassisk korsrygg-øvelse." },
  { id:"r33", name:"Good morning",                  eng:"Good Morning",                group:"rygg",   equipment:"stang",     level:"middels",   sets:"3 x 8",     desc:"Stang på rygg - bøy fram i hofte." },
  { id:"r34", name:"Rack pull",                     eng:"Rack Pull",                   group:"rygg",   equipment:"stang",     level:"middels",   sets:"4 x 5",     desc:"Markløft fra hofte-høyde - tung topp ROM." },
  { id:"r35", name:"Snatch grip deadlift",          eng:"Snatch-Grip Deadlift",        group:"rygg",   equipment:"stang",     level:"erfaren",   sets:"3 x 5",     desc:"Bredt grep - mer øvre rygg." },

  // ── SKULDRE (30) ──
  { id:"s1",  name:"Stående stangpress",            eng:"Overhead Press (OHP)",        group:"skuldre",equipment:"stang",     level:"middels",   sets:"4 x 6",     desc:"Stående press fra skuldre over hode." },
  { id:"s2",  name:"Sittende stangpress",           eng:"Seated Barbell Press",        group:"skuldre",equipment:"stang",     level:"middels",   sets:"4 x 8",     desc:"Mindre kjerneaktivering - mer fokus på skuldre." },
  { id:"s3",  name:"Push press",                    eng:"Push Press",                  group:"skuldre",equipment:"stang",     level:"erfaren",   sets:"4 x 5",     desc:"Bruk bena til å hjelpe stang over hode." },
  { id:"s4",  name:"Manualpress",                   eng:"Dumbbell Shoulder Press",     group:"skuldre",equipment:"manual",    level:"begynner",  sets:"4 x 8-10",  desc:"Standard manualpress - sittende eller stående." },
  { id:"s5",  name:"Arnold press",                  eng:"Arnold Press",                group:"skuldre",equipment:"manual",    level:"middels",   sets:"3 x 10",    desc:"Roter manualer på vei opp - hele delt aktiveres." },
  { id:"s6",  name:"Sidehev manual",                eng:"Lateral Raise",               group:"skuldre",equipment:"manual",    level:"begynner",  sets:"4 x 12",    desc:"Klassisk - hev manualer rett ut til siden." },
  { id:"s7",  name:"Cable sidehev",                 eng:"Cable Lateral Raise",         group:"skuldre",equipment:"kabel",     level:"begynner",  sets:"3 x 15",    desc:"Konstant motstand - bedre topp-kontraksjon." },
  { id:"s8",  name:"Maskin sidehev",                eng:"Lateral Raise Machine",       group:"skuldre",equipment:"maskin",    level:"begynner",  sets:"3 x 12",    desc:"Maskinvariant for nybegynnere." },
  { id:"s9",  name:"Bent-over reverse fly",         eng:"Reverse Fly",                 group:"skuldre",equipment:"manual",    level:"begynner",  sets:"3 x 15",    desc:"Bøyd - hev manualer ut bakover. Bakre delt." },
  { id:"s10", name:"Cable reverse fly",             eng:"Cable Reverse Fly",           group:"skuldre",equipment:"kabel",     level:"middels",   sets:"3 x 12",    desc:"Reverse fly på kabel." },
  { id:"s11", name:"Reverse pec deck",              eng:"Reverse Pec Deck",            group:"skuldre",equipment:"maskin",    level:"begynner",  sets:"3 x 15",    desc:"Sittende - hev armer bakover. Bakre delt." },
  { id:"s12", name:"Manual front raise",            eng:"Front Raise",                 group:"skuldre",equipment:"manual",    level:"begynner",  sets:"3 x 12",    desc:"Løft manualer rett fram for fremre delt." },
  { id:"s13", name:"Stang front raise",             eng:"Barbell Front Raise",         group:"skuldre",equipment:"stang",     level:"begynner",  sets:"3 x 10",    desc:"Stang løftes rett fram." },
  { id:"s14", name:"Cable front raise",             eng:"Cable Front Raise",           group:"skuldre",equipment:"kabel",     level:"begynner",  sets:"3 x 12",    desc:"Konstant motstand for fremre delt." },
  { id:"s15", name:"Upright row",                   eng:"Upright Row",                 group:"skuldre",equipment:"stang",     level:"middels",   sets:"3 x 10",    desc:"Trekk stangen opp langs kroppen - delt og trapp." },
  { id:"s16", name:"Manual upright row",            eng:"Dumbbell Upright Row",        group:"skuldre",equipment:"manual",    level:"middels",   sets:"3 x 12",    desc:"Manualer - bedre for skuldre enn stang." },
  { id:"s17", name:"Snatch-grip high pull",         eng:"Snatch-Grip High Pull",       group:"skuldre",equipment:"stang",     level:"erfaren",   sets:"3 x 5",     desc:"Eksplosiv high pull - hele delt." },
  { id:"s18", name:"Lateral cable single-arm",      eng:"Single-Arm Cable Lateral",    group:"skuldre",equipment:"kabel",     level:"middels",   sets:"3 x 12",    desc:"En arm av gangen - bedre kontroll." },
  { id:"s19", name:"Y-raise",                       eng:"Y-Raise",                     group:"skuldre",equipment:"manual",    level:"begynner",  sets:"3 x 12",    desc:"Skrå benk - løft manualer i Y." },
  { id:"s20", name:"T-raise",                       eng:"T-Raise",                     group:"skuldre",equipment:"manual",    level:"begynner",  sets:"3 x 12",    desc:"Skrå benk - løft i T-form." },
  { id:"s21", name:"Cuban press",                   eng:"Cuban Press",                 group:"skuldre",equipment:"manual",    level:"middels",   sets:"3 x 10",    desc:"Upright row + rotasjon + press." },
  { id:"s22", name:"Z-press",                       eng:"Z-Press",                     group:"skuldre",equipment:"stang",     level:"erfaren",   sets:"3 x 6",     desc:"Sittende på gulv - utfordrer kjerne." },
  { id:"s23", name:"Bottoms-up KB press",           eng:"Bottoms-Up KB Press",         group:"skuldre",equipment:"kettlebell",level:"erfaren",   sets:"3 x 8",     desc:"Kettlebell opp-ned - grep og rotator." },
  { id:"s24", name:"Handstand pushup",              eng:"Handstand Push-up",           group:"skuldre",equipment:"kroppsvekt",level:"erfaren",   sets:"3 x 5",     desc:"Hodet ned mot vegg - vertikal press." },
  { id:"s25", name:"Pike pushup",                   eng:"Pike Push-up",                group:"skuldre",equipment:"kroppsvekt",level:"middels",   sets:"3 x 10",    desc:"Pike-stilling - skulder-dominant pushup." },
  { id:"s26", name:"Landmine press",                eng:"Landmine Press",              group:"skuldre",equipment:"stang",     level:"middels",   sets:"3 x 10",    desc:"Stang i hjørne - press i diagonal." },
  { id:"s27", name:"Behind-the-neck press",         eng:"Behind-the-Neck Press",       group:"skuldre",equipment:"stang",     level:"erfaren",   sets:"3 x 8",     desc:"Press bak nakken - kun erfarne." },
  { id:"s28", name:"Bradford press",                eng:"Bradford Press",              group:"skuldre",equipment:"stang",     level:"erfaren",   sets:"3 x 10",    desc:"Vekselsvis foran og bak nakken." },
  { id:"s29", name:"Viking press",                  eng:"Viking Press",                group:"skuldre",equipment:"stang",     level:"middels",   sets:"3 x 8",     desc:"Landmine med håndtak - bilateralt." },
  { id:"s30", name:"Powell raise",                  eng:"Powell Raise",                group:"skuldre",equipment:"manual",    level:"middels",   sets:"3 x 12",    desc:"Ligg på siden - hev manual i halvbue." },

  // ── BICEP (25) ──
  { id:"bi1", name:"Bicepscurl stang",              eng:"Barbell Curl",                group:"bicep",  equipment:"stang",     level:"begynner",  sets:"4 x 10",    desc:"Klassisk - hold albuene festet til siden." },
  { id:"bi2", name:"EZ-bar curl",                   eng:"EZ-Bar Curl",                 group:"bicep",  equipment:"stang",     level:"begynner",  sets:"3 x 10",    desc:"Svebar - vennligere for håndledd." },
  { id:"bi3", name:"Manualcurl alternerende",       eng:"Alternating Dumbbell Curl",   group:"bicep",  equipment:"manual",    level:"begynner",  sets:"3 x 12",    desc:"Vekselsvis - kan supinere håndleddet." },
  { id:"bi4", name:"Hammer curl",                   eng:"Hammer Curl",                 group:"bicep",  equipment:"manual",    level:"begynner",  sets:"3 x 12",    desc:"Nøytralt grep - brachialis og brachioradialis." },
  { id:"bi5", name:"Cross-body hammer curl",        eng:"Cross-Body Hammer Curl",      group:"bicep",  equipment:"manual",    level:"begynner",  sets:"3 x 10",    desc:"Curl over mot motsatt skulder." },
  { id:"bi6", name:"Concentration curl",            eng:"Concentration Curl",          group:"bicep",  equipment:"manual",    level:"begynner",  sets:"3 x 12",    desc:"Sittende - albue på låret. Maks isolasjon." },
  { id:"bi7", name:"Preacher curl",                 eng:"Preacher Curl",               group:"bicep",  equipment:"stang",     level:"middels",   sets:"3 x 10",    desc:"Skråbenk - eliminerer juks." },
  { id:"bi8", name:"Spider curl",                   eng:"Spider Curl",                 group:"bicep",  equipment:"manual",    level:"middels",   sets:"3 x 12",    desc:"Ligg framlent på skrå benk." },
  { id:"bi9", name:"Incline manual curl",           eng:"Incline Dumbbell Curl",       group:"bicep",  equipment:"manual",    level:"middels",   sets:"3 x 10",    desc:"Skråbenk - bicep strekkes maks." },
  { id:"bi10",name:"Cable curl med stang",          eng:"Cable Bar Curl",              group:"bicep",  equipment:"kabel",     level:"begynner",  sets:"3 x 12",    desc:"Konstant motstand fra kabel." },
  { id:"bi11",name:"Cable hammer curl (rep)",       eng:"Cable Hammer Curl",           group:"bicep",  equipment:"kabel",     level:"begynner",  sets:"3 x 12",    desc:"Rep-grep på kabel." },
  { id:"bi12",name:"Cable curl over hode",          eng:"Overhead Cable Curl",         group:"bicep",  equipment:"kabel",     level:"middels",   sets:"3 x 12",    desc:"Står mellom to kabler - curl mot hode." },
  { id:"bi13",name:"21s",                           eng:"21s",                         group:"bicep",  equipment:"stang",     level:"middels",   sets:"3 x 21",    desc:"7 halv-bunn + 7 halv-topp + 7 hele." },
  { id:"bi14",name:"Zottman curl",                  eng:"Zottman Curl",                group:"bicep",  equipment:"manual",    level:"middels",   sets:"3 x 10",    desc:"Curl opp normalt, snu håndleddet og senk." },
  { id:"bi15",name:"Reverse curl",                  eng:"Reverse Curl",                group:"bicep",  equipment:"stang",     level:"begynner",  sets:"3 x 12",    desc:"Overhåndsgrep - brachialis og underarm." },
  { id:"bi16",name:"Drag curl",                     eng:"Drag Curl",                   group:"bicep",  equipment:"stang",     level:"middels",   sets:"3 x 10",    desc:"Trekk stang opp langs kroppen." },
  { id:"bi17",name:"Bayesian curl",                 eng:"Bayesian Curl",               group:"bicep",  equipment:"kabel",     level:"middels",   sets:"3 x 12",    desc:"Kabel bak - maksimal strekk på bicep." },
  { id:"bi18",name:"Inkline hammer curl",           eng:"Incline Hammer Curl",         group:"bicep",  equipment:"manual",    level:"middels",   sets:"3 x 12",    desc:"Skråbenk hammer." },
  { id:"bi19",name:"Cheat curl",                    eng:"Cheat Curl",                  group:"bicep",  equipment:"stang",     level:"erfaren",   sets:"3 x 6",     desc:"Bruk litt momentum - tung vekt." },
  { id:"bi20",name:"Maskin curl",                   eng:"Machine Curl",                group:"bicep",  equipment:"maskin",    level:"begynner",  sets:"3 x 12",    desc:"Sittende maskinvariant." },
  { id:"bi21",name:"Wide grip bicepscurl",          eng:"Wide-Grip Curl",              group:"bicep",  equipment:"stang",     level:"begynner",  sets:"3 x 10",    desc:"Bredt grep - mer indre bicep-hode." },
  { id:"bi22",name:"Narrow grip curl",              eng:"Narrow-Grip Curl",            group:"bicep",  equipment:"stang",     level:"begynner",  sets:"3 x 10",    desc:"Smalt grep - mer ytre bicep-hode." },
  { id:"bi23",name:"Towel pull-up",                 eng:"Towel Pull-up",               group:"bicep",  equipment:"kroppsvekt",level:"erfaren",   sets:"3 x 6",     desc:"Pull-up med håndklær - grep og bicep." },
  { id:"bi24",name:"Chin-up med pause",             eng:"Chin-up with Hold",           group:"bicep",  equipment:"kroppsvekt",level:"middels",   sets:"3 x maks",  desc:"Pause på topp i 2 sek." },
  { id:"bi25",name:"Banded curl",                   eng:"Banded Curl",                 group:"bicep",  equipment:"bånd",      level:"begynner",  sets:"3 x 15",    desc:"Curl med elastikkbånd." },

  // ── TRICEP (25) ──
  { id:"t1",  name:"Close-grip benkpress",          eng:"Close-Grip Bench Press",      group:"tricep", equipment:"stang",     level:"middels",   sets:"4 x 6-8",   desc:"Smalt grep - sterk tricep-vekst." },
  { id:"t2",  name:"Tricep dips",                   eng:"Tricep Dips",                 group:"tricep", equipment:"kroppsvekt",level:"middels",   sets:"3 x 10",    desc:"Oppreist torso - vekt på tricep." },
  { id:"t3",  name:"Benkdips",                      eng:"Bench Dips",                  group:"tricep", equipment:"kroppsvekt",level:"begynner",  sets:"3 x 12",    desc:"Hender på benk bak - dipp." },
  { id:"t4",  name:"Skullcrusher EZ",               eng:"EZ-Bar Skullcrusher",         group:"tricep", equipment:"stang",     level:"middels",   sets:"3 x 10",    desc:"Liggende - senk stang mot panne." },
  { id:"t5",  name:"Manual skullcrusher",           eng:"DB Skullcrusher",             group:"tricep", equipment:"manual",    level:"middels",   sets:"3 x 10",    desc:"Manualer i stedet for stang." },
  { id:"t6",  name:"Tricep pushdown (rep)",         eng:"Rope Pushdown",               group:"tricep", equipment:"kabel",     level:"begynner",  sets:"3 x 12",    desc:"Klassisk - rep-håndtak." },
  { id:"t7",  name:"Tricep pushdown (stang)",       eng:"Bar Pushdown",                group:"tricep", equipment:"kabel",     level:"begynner",  sets:"3 x 12",    desc:"Stang-håndtak - litt mer tung." },
  { id:"t8",  name:"Overhead tricep extension",     eng:"Overhead Tricep Extension",   group:"tricep", equipment:"manual",    level:"begynner",  sets:"3 x 12",    desc:"Strekk manual over hode." },
  { id:"t9",  name:"Overhead cable extension",      eng:"Overhead Cable Extension",    group:"tricep", equipment:"kabel",     level:"middels",   sets:"3 x 12",    desc:"Kabel bak - strekk på lange hode." },
  { id:"t10", name:"Cable kickback",                eng:"Cable Tricep Kickback",       group:"tricep", equipment:"kabel",     level:"begynner",  sets:"3 x 12",    desc:"Bøyd - strekk armen bakover." },
  { id:"t11", name:"Manual kickback",               eng:"Dumbbell Kickback",           group:"tricep", equipment:"manual",    level:"begynner",  sets:"3 x 12",    desc:"En arm - kne på benk." },
  { id:"t12", name:"Diamond pushup",                eng:"Diamond Push-up",             group:"tricep", equipment:"kroppsvekt",level:"middels",   sets:"3 x 10",    desc:"Smale armer - tricep-fokus." },
  { id:"t13", name:"JM press",                      eng:"JM Press",                    group:"tricep", equipment:"stang",     level:"erfaren",   sets:"3 x 6",     desc:"Hybrid skull + close grip bench." },
  { id:"t14", name:"Tate press",                    eng:"Tate Press",                  group:"tricep", equipment:"manual",    level:"middels",   sets:"3 x 10",    desc:"Liggende - manualer ned mot bryst i V." },
  { id:"t15", name:"California press",              eng:"California Press",            group:"tricep", equipment:"stang",     level:"erfaren",   sets:"3 x 8",     desc:"Skullcrusher som glir til bench." },
  { id:"t16", name:"Cable rope extension over",     eng:"Rope Overhead Extension",     group:"tricep", equipment:"kabel",     level:"begynner",  sets:"3 x 12",    desc:"Bøyd fram - kabel rep over hode." },
  { id:"t17", name:"Reverse grip pushdown",         eng:"Reverse-Grip Pushdown",       group:"tricep", equipment:"kabel",     level:"begynner",  sets:"3 x 12",    desc:"Undergrep pushdown - medialhode." },
  { id:"t18", name:"Single-arm pushdown",           eng:"Single-Arm Pushdown",         group:"tricep", equipment:"kabel",     level:"middels",   sets:"3 x 12",    desc:"En arm - bedre topp-kontraksjon." },
  { id:"t19", name:"Smith narrow press",            eng:"Smith Narrow Press",          group:"tricep", equipment:"smith",     level:"begynner",  sets:"3 x 10",    desc:"Smal benkpress i Smith." },
  { id:"t20", name:"Bench dip vektet",              eng:"Weighted Bench Dip",          group:"tricep", equipment:"kroppsvekt",level:"erfaren",   sets:"3 x 12",    desc:"Tilleggsvekt på låret." },
  { id:"t21", name:"Tricep extension maskin",       eng:"Tricep Extension Machine",    group:"tricep", equipment:"maskin",    level:"begynner",  sets:"3 x 12",    desc:"Sittende maskinvariant." },
  { id:"t22", name:"Bench rep extension",           eng:"Lying Rope Extension",        group:"tricep", equipment:"kabel",     level:"middels",   sets:"3 x 12",    desc:"Ligg på benk - rep over hode." },
  { id:"t23", name:"Dip-press hybrid",              eng:"Ring Dip",                    group:"tricep", equipment:"kroppsvekt",level:"erfaren",   sets:"3 x 8",     desc:"Dipper i ringer - stabilitet." },
  { id:"t24", name:"PJR pullover",                  eng:"PJR Pullover",                group:"tricep", equipment:"stang",     level:"middels",   sets:"3 x 10",    desc:"Hybrid pullover + skullcrusher." },
  { id:"t25", name:"Tricep press maskin",           eng:"Machine Tricep Press",        group:"tricep", equipment:"maskin",    level:"begynner",  sets:"3 x 12",    desc:"Dip-maskin variant." },

  // ── UNDERARM / GREP (15) ──
  { id:"u1",  name:"Farmer's walk",                 eng:"Farmer's Walk",               group:"underarm",equipment:"manual",   level:"middels",   sets:"3 x 30 m",  desc:"Bær tunge manualer - grep og kjerne." },
  { id:"u2",  name:"Stang dead hang",               eng:"Dead Hang",                   group:"underarm",equipment:"kroppsvekt",level:"begynner", sets:"3 x maks tid",desc:"Heng i stang - grep, mobilitet." },
  { id:"u3",  name:"Pinch grip plate hold",         eng:"Plate Pinch Hold",            group:"underarm",equipment:"manual",   level:"middels",   sets:"3 x 30 s",  desc:"Klem skive med fingre - grep." },
  { id:"u4",  name:"Wrist curl",                    eng:"Wrist Curl",                  group:"underarm",equipment:"stang",    level:"begynner",  sets:"3 x 15",    desc:"Underhånds - rull stang i håndledd." },
  { id:"u5",  name:"Reverse wrist curl",            eng:"Reverse Wrist Curl",          group:"underarm",equipment:"stang",    level:"begynner",  sets:"3 x 15",    desc:"Overhånds - underarmens ytre side." },
  { id:"u6",  name:"Reverse curl (svebar)",         eng:"EZ Reverse Curl",             group:"underarm",equipment:"stang",    level:"begynner",  sets:"3 x 12",    desc:"Brachioradialis + underarm." },
  { id:"u7",  name:"Towel pull-up",                 eng:"Towel Pull-up",               group:"underarm",equipment:"kroppsvekt",level:"erfaren",  sets:"3 x 6",     desc:"Heng i håndkle - grep utfordres." },
  { id:"u8",  name:"Captains of Crush",             eng:"Hand Gripper",                group:"underarm",equipment:"manual",   level:"middels",   sets:"3 x maks",  desc:"Grip-trener - tett hånden 100%." },
  { id:"u9",  name:"Wrist roller",                  eng:"Wrist Roller",                group:"underarm",equipment:"manual",   level:"middels",   sets:"3 ruller",  desc:"Roll vekten opp på pinne." },
  { id:"u10", name:"Hex hold",                      eng:"Hex Hold",                    group:"underarm",equipment:"manual",   level:"begynner",  sets:"3 x 30 s",  desc:"Hold heksagonal manual ved enden." },
  { id:"u11", name:"Hammer curl med pause",         eng:"Hammer Hold",                 group:"underarm",equipment:"manual",   level:"middels",   sets:"3 x 8",     desc:"Hammer curl med 3 sek pause på topp." },
  { id:"u12", name:"Behind back wrist curl",        eng:"Behind-Back Wrist Curl",      group:"underarm",equipment:"stang",    level:"begynner",  sets:"3 x 15",    desc:"Stang bak ryggen - rull i hånd." },
  { id:"u13", name:"Plate raise hold",              eng:"Plate Front Raise Hold",      group:"underarm",equipment:"manual",   level:"begynner",  sets:"3 x 20 s",  desc:"Hold skive fram - delt og grep." },
  { id:"u14", name:"Bottoms-up KB hold",            eng:"Bottoms-Up KB Hold",          group:"underarm",equipment:"kettlebell",level:"erfaren",  sets:"3 x 20 s",  desc:"KB opp-ned - grep + skulder." },
  { id:"u15", name:"Thick-bar curl",                eng:"Fat-Grip Curl",                group:"underarm",equipment:"stang",    level:"middels",   sets:"3 x 10",    desc:"Tykk-grep curl - utfordrer underarm." },

  // ── QUAD / LÅR FREMSIDE (30) ──
  { id:"q1",  name:"Knebøy (back squat)",           eng:"Back Squat",                  group:"quad",   equipment:"stang",     level:"middels",   sets:"4 x 5-8",   desc:"Klassisk - stang på øvre rygg." },
  { id:"q2",  name:"Front squat",                   eng:"Front Squat",                 group:"quad",   equipment:"stang",     level:"middels",   sets:"4 x 5",     desc:"Stang foran - mer quad og kjerne." },
  { id:"q3",  name:"High-bar squat",                eng:"High-Bar Squat",              group:"quad",   equipment:"stang",     level:"middels",   sets:"4 x 6",     desc:"Stang høyt - oppreist - quad-dominant." },
  { id:"q4",  name:"Low-bar squat",                 eng:"Low-Bar Squat",               group:"quad",   equipment:"stang",     level:"middels",   sets:"4 x 5",     desc:"Stang lavt - mer hofte og glute." },
  { id:"q5",  name:"Goblet squat",                  eng:"Goblet Squat",                group:"quad",   equipment:"manual",    level:"begynner",  sets:"3 x 10",    desc:"Hold manual mot brystet - knebøy." },
  { id:"q6",  name:"Bulgarian split squat",         eng:"Bulgarian Split Squat",       group:"quad",   equipment:"manual",    level:"middels",   sets:"3 x 8 pr.bein", desc:"Bakerste bein opp på benk." },
  { id:"q7",  name:"Smith squat",                   eng:"Smith Machine Squat",         group:"quad",   equipment:"smith",     level:"begynner",  sets:"4 x 8",     desc:"Guidet stang - lettere balanse." },
  { id:"q8",  name:"Beinpress",                     eng:"Leg Press",                   group:"quad",   equipment:"maskin",    level:"begynner",  sets:"4 x 10",    desc:"Press platen bort - mye vekt mulig." },
  { id:"q9",  name:"Hack squat",                    eng:"Hack Squat",                  group:"quad",   equipment:"maskin",    level:"middels",   sets:"3 x 8",     desc:"Maskinvariant - mer quad." },
  { id:"q10", name:"Sittende beinstrekk",           eng:"Leg Extension",               group:"quad",   equipment:"maskin",    level:"begynner",  sets:"3 x 12",    desc:"Isolert quad-strekk." },
  { id:"q11", name:"Walking lunge",                 eng:"Walking Lunge",               group:"quad",   equipment:"manual",    level:"begynner",  sets:"3 x 12 pr.bein", desc:"Gående utfall." },
  { id:"q12", name:"Reverse lunge",                 eng:"Reverse Lunge",               group:"quad",   equipment:"manual",    level:"begynner",  sets:"3 x 10 pr.bein", desc:"Steg bakover - knæ-vennlig." },
  { id:"q13", name:"Forward lunge",                 eng:"Forward Lunge",               group:"quad",   equipment:"manual",    level:"begynner",  sets:"3 x 10 pr.bein", desc:"Steg fremover - vanlig utfall." },
  { id:"q14", name:"Box squat",                     eng:"Box Squat",                   group:"quad",   equipment:"stang",     level:"middels",   sets:"4 x 5",     desc:"Sette seg på boks - kontroll." },
  { id:"q15", name:"Pause squat",                   eng:"Pause Squat",                 group:"quad",   equipment:"stang",     level:"middels",   sets:"3 x 5",     desc:"3 sek pause i bunn av knebøy." },
  { id:"q16", name:"Tempo squat",                   eng:"Tempo Squat",                 group:"quad",   equipment:"stang",     level:"middels",   sets:"3 x 5 (3-1-1)", desc:"Senk i 3 sek, 1 sek pause, opp." },
  { id:"q17", name:"Sissy squat",                   eng:"Sissy Squat",                 group:"quad",   equipment:"kroppsvekt",level:"erfaren",   sets:"3 x 8",     desc:"Bøy bakover på knærne - quad-strekk." },
  { id:"q18", name:"Spanish squat",                 eng:"Spanish Squat",               group:"quad",   equipment:"bånd",      level:"begynner",  sets:"3 x 12",    desc:"Bånd rundt knær - knæ-vennlig." },
  { id:"q19", name:"Step-up",                       eng:"Step-up",                     group:"quad",   equipment:"manual",    level:"begynner",  sets:"3 x 10 pr.bein", desc:"Tråkk opp på benk." },
  { id:"q20", name:"Bulgarian smith",               eng:"Smith Bulgarian Split",       group:"quad",   equipment:"smith",     level:"middels",   sets:"3 x 10",    desc:"Bulgarian i Smith - stabilt." },
  { id:"q21", name:"Pistol squat",                  eng:"Pistol Squat",                group:"quad",   equipment:"kroppsvekt",level:"erfaren",   sets:"3 x 5 pr.bein",  desc:"Ett bein - dyp knebøy." },
  { id:"q22", name:"Cossack squat",                 eng:"Cossack Squat",               group:"quad",   equipment:"manual",    level:"middels",   sets:"3 x 8 pr.bein",  desc:"Side-til-side bredt utfall." },
  { id:"q23", name:"Front foot elevated lunge",     eng:"Elevated Lunge",              group:"quad",   equipment:"manual",    level:"middels",   sets:"3 x 10",    desc:"Fremre fot på platta." },
  { id:"q24", name:"Banded squat",                  eng:"Banded Squat",                group:"quad",   equipment:"bånd",      level:"begynner",  sets:"3 x 15",    desc:"Bånd rundt knær - aktiver glute." },
  { id:"q25", name:"Wall sit",                      eng:"Wall Sit",                    group:"quad",   equipment:"kroppsvekt",level:"begynner",  sets:"3 x 45 s",  desc:"Sitt mot vegg - isometrisk hold." },
  { id:"q26", name:"Belt squat",                    eng:"Belt Squat",                  group:"quad",   equipment:"maskin",    level:"middels",   sets:"3 x 10",    desc:"Vekt på beltet - rygg avlastes." },
  { id:"q27", name:"Zercher squat",                 eng:"Zercher Squat",               group:"quad",   equipment:"stang",     level:"erfaren",   sets:"3 x 6",     desc:"Stang i albuene - oppreist torso." },
  { id:"q28", name:"Safety bar squat",              eng:"Safety Bar Squat",            group:"quad",   equipment:"stang",     level:"middels",   sets:"4 x 6",     desc:"Spesialstang - vennligere skuldre." },
  { id:"q29", name:"Heels-elevated squat",          eng:"Heel-Elevated Squat",         group:"quad",   equipment:"stang",     level:"middels",   sets:"3 x 10",    desc:"Hælene hevet - mer quad." },
  { id:"q30", name:"Sled push",                     eng:"Sled Push",                   group:"quad",   equipment:"maskin",    level:"middels",   sets:"4 x 20 m",  desc:"Skyv slede - hele bein og hjerte." },

  // ── HAMSTRING / LÅR BAKSIDE (20) ──
  { id:"h1",  name:"Romersk markløft",              eng:"Romanian Deadlift",           group:"ham",    equipment:"stang",     level:"middels",   sets:"4 x 8",     desc:"Bøy i hofte - strekk på baksiden." },
  { id:"h2",  name:"Single-leg RDL",                eng:"Single-Leg RDL",              group:"ham",    equipment:"manual",    level:"middels",   sets:"3 x 8 pr.bein", desc:"En manual - balanse + hams." },
  { id:"h3",  name:"Leg curl liggende",             eng:"Lying Leg Curl",              group:"ham",    equipment:"maskin",    level:"begynner",  sets:"3 x 12",    desc:"Maskin - bøy kne på maskin." },
  { id:"h4",  name:"Leg curl sittende",             eng:"Seated Leg Curl",             group:"ham",    equipment:"maskin",    level:"begynner",  sets:"3 x 12",    desc:"Sittende - bøy kne mot baken." },
  { id:"h5",  name:"Single-leg curl",               eng:"Single Leg Curl",             group:"ham",    equipment:"maskin",    level:"middels",   sets:"3 x 10",    desc:"Ett bein om gangen." },
  { id:"h6",  name:"Nordic curl",                   eng:"Nordic Hamstring Curl",       group:"ham",    equipment:"kroppsvekt",level:"erfaren",   sets:"3 x 5",     desc:"Senk kroppen langsomt fra knestående." },
  { id:"h7",  name:"Glute-ham raise",               eng:"Glute-Ham Raise (GHR)",       group:"ham",    equipment:"maskin",    level:"erfaren",   sets:"3 x 8",     desc:"GHR-benk - bøy + strekk." },
  { id:"h8",  name:"Reverse hyper",                 eng:"Reverse Hyperextension",      group:"ham",    equipment:"maskin",    level:"middels",   sets:"3 x 12",    desc:"Hev bena bakover - hams og glute." },
  { id:"h9",  name:"Single-leg hip thrust",         eng:"Single-Leg Hip Thrust",       group:"ham",    equipment:"kroppsvekt",level:"middels",   sets:"3 x 10",    desc:"Ett bein - skuldre på benk." },
  { id:"h10", name:"Stiff-leg deadlift",            eng:"Stiff-Leg Deadlift",          group:"ham",    equipment:"stang",     level:"middels",   sets:"3 x 8",     desc:"Strake bein - maks hams-strekk." },
  { id:"h11", name:"Cable pull-through",             eng:"Cable Pull-Through",          group:"ham",    equipment:"kabel",     level:"begynner",  sets:"3 x 12",    desc:"Kabel mellom bena - hofte-bevegelse." },
  { id:"h12", name:"Banded good morning",           eng:"Banded Good Morning",         group:"ham",    equipment:"bånd",      level:"begynner",  sets:"3 x 12",    desc:"Bånd over rygg - bøy framover." },
  { id:"h13", name:"Stang good morning",            eng:"Barbell Good Morning",        group:"ham",    equipment:"stang",     level:"middels",   sets:"3 x 8",     desc:"Stang på rygg - hofte-bøy." },
  { id:"h14", name:"Swiss ball leg curl",           eng:"Swiss Ball Leg Curl",         group:"ham",    equipment:"kroppsvekt",level:"begynner",  sets:"3 x 12",    desc:"Hælene på ball - trekk mot baken." },
  { id:"h15", name:"Sliding leg curl",              eng:"Sliding Leg Curl",            group:"ham",    equipment:"kroppsvekt",level:"middels",   sets:"3 x 10",    desc:"Hælene på slidere - hofte oppe, curl." },
  { id:"h16", name:"Deficit RDL",                   eng:"Deficit RDL",                 group:"ham",    equipment:"stang",     level:"erfaren",   sets:"3 x 8",     desc:"Stå på platå - dypere ROM." },
  { id:"h17", name:"Snatch grip RDL",               eng:"Snatch-Grip RDL",             group:"ham",    equipment:"stang",     level:"erfaren",   sets:"3 x 6",     desc:"Bredt grep - mer rygg." },
  { id:"h18", name:"Razor curl",                    eng:"Razor Curl",                  group:"ham",    equipment:"kroppsvekt",level:"erfaren",   sets:"3 x 8",     desc:"GHR-variant - knestående." },
  { id:"h19", name:"Hamstring slide-out",           eng:"Hamstring Slide-Out",         group:"ham",    equipment:"kroppsvekt",level:"middels",   sets:"3 x 10",    desc:"Hælene på sliders - strekk og bøy." },
  { id:"h20", name:"Kettlebell swing",              eng:"Kettlebell Swing",            group:"ham",    equipment:"kettlebell",level:"middels",   sets:"3 x 15",    desc:"Hofte-eksplosivitet - bakkjede." },

  // ── GLUTE / SETER (25) ──
  { id:"g1",  name:"Hip thrust (stang)",            eng:"Barbell Hip Thrust",          group:"glute",  equipment:"stang",     level:"middels",   sets:"4 x 8",     desc:"Skuldre på benk - press hofte opp." },
  { id:"g2",  name:"Glute bridge",                  eng:"Glute Bridge",                group:"glute",  equipment:"kroppsvekt",level:"begynner",  sets:"3 x 15",    desc:"Ligg på rygg - press hofte opp." },
  { id:"g3",  name:"Single-leg glute bridge",       eng:"Single-Leg Glute Bridge",     group:"glute",  equipment:"kroppsvekt",level:"begynner",  sets:"3 x 12 pr.bein", desc:"Ett bein - ekstra glute-fokus." },
  { id:"g4",  name:"Cable kickback",                eng:"Cable Glute Kickback",        group:"glute",  equipment:"kabel",     level:"begynner",  sets:"3 x 15",    desc:"Spark beinet bakover med kabel." },
  { id:"g5",  name:"Banded clamshell",              eng:"Clamshell",                   group:"glute",  equipment:"bånd",      level:"begynner",  sets:"3 x 15",    desc:"Sideligg - åpne knær mot bånd." },
  { id:"g6",  name:"Lateral band walk",             eng:"Lateral Band Walk",           group:"glute",  equipment:"bånd",      level:"begynner",  sets:"3 x 15 hver vei", desc:"Bånd om knær - gå sidelengs." },
  { id:"g7",  name:"Monster walk",                  eng:"Monster Walk",                group:"glute",  equipment:"bånd",      level:"begynner",  sets:"3 x 15",    desc:"Bånd om ankler - gå diagonalt." },
  { id:"g8",  name:"Sumo deadlift",                 eng:"Sumo Deadlift",               group:"glute",  equipment:"stang",     level:"middels",   sets:"4 x 5",     desc:"Bred standing - mer glute-aktivering." },
  { id:"g9",  name:"Curtsy lunge",                  eng:"Curtsy Lunge",                group:"glute",  equipment:"manual",    level:"middels",   sets:"3 x 10 pr.bein", desc:"Steg bak diagonalt - glute medius." },
  { id:"g10", name:"Frog pumps",                    eng:"Frog Pumps",                  group:"glute",  equipment:"kroppsvekt",level:"begynner",  sets:"3 x 25",    desc:"Føtter sammen, hofte opp - frosk-form." },
  { id:"g11", name:"Cable hip abduction",           eng:"Cable Hip Abduction",         group:"glute",  equipment:"kabel",     level:"begynner",  sets:"3 x 15",    desc:"Bein til siden mot kabel." },
  { id:"g12", name:"Maskin hip abduction",          eng:"Hip Abduction Machine",       group:"glute",  equipment:"maskin",    level:"begynner",  sets:"3 x 15",    desc:"Sittende - sprek bena fra hverandre." },
  { id:"g13", name:"Maskin hip adduction",          eng:"Hip Adduction Machine",       group:"glute",  equipment:"maskin",    level:"begynner",  sets:"3 x 15",    desc:"Sittende - klem bena sammen." },
  { id:"g14", name:"B-stance hip thrust",           eng:"B-Stance Hip Thrust",         group:"glute",  equipment:"manual",    level:"middels",   sets:"3 x 12",    desc:"Hælet på arbeidsbeinet, tå på støttebenet." },
  { id:"g15", name:"45-graders hyperextension",     eng:"45° Back Extension (glute)",  group:"glute",  equipment:"maskin",    level:"begynner",  sets:"3 x 15",    desc:"Rund rygg - glute-fokus." },
  { id:"g16", name:"Step-up høy benk",              eng:"High Box Step-up",            group:"glute",  equipment:"manual",    level:"middels",   sets:"3 x 8 pr.bein", desc:"Høy benk - mer glute." },
  { id:"g17", name:"Glute kickback maskin",         eng:"Glute Kickback Machine",      group:"glute",  equipment:"maskin",    level:"begynner",  sets:"3 x 12",    desc:"Maskin - spark beinet bakover." },
  { id:"g18", name:"Sumo squat",                    eng:"Sumo Squat",                  group:"glute",  equipment:"manual",    level:"begynner",  sets:"3 x 12",    desc:"Bredt fotstilling - mer glute." },
  { id:"g19", name:"Standing cable abduction",      eng:"Standing Cable Abduction",    group:"glute",  equipment:"kabel",     level:"begynner",  sets:"3 x 15",    desc:"Stå - svinge beinet ut." },
  { id:"g20", name:"Standing hip thrust",           eng:"Standing Hip Thrust",         group:"glute",  equipment:"kabel",     level:"middels",   sets:"3 x 12",    desc:"Stå med kabel om hofta - thrust." },
  { id:"g21", name:"Reverse hyper (glute)",         eng:"Reverse Hyper Glute",         group:"glute",  equipment:"maskin",    level:"middels",   sets:"3 x 12",    desc:"Fokus på topp-kontraksjon." },
  { id:"g22", name:"Hip thrust maskin",             eng:"Hip Thrust Machine",          group:"glute",  equipment:"maskin",    level:"begynner",  sets:"3 x 12",    desc:"Dedikert hip thrust-maskin." },
  { id:"g23", name:"Kas glute bridge",              eng:"Kas Glute Bridge",            group:"glute",  equipment:"manual",    level:"middels",   sets:"3 x 12",    desc:"Halv-ROM på topp - maks klem." },
  { id:"g24", name:"Glute focus deadlift",          eng:"Glute-Focused Deadlift",      group:"glute",  equipment:"stang",     level:"middels",   sets:"3 x 8",     desc:"Lock-out med skvis på topp." },
  { id:"g25", name:"Single-leg deadlift",           eng:"Single-Leg Deadlift",         group:"glute",  equipment:"manual",    level:"middels",   sets:"3 x 8 pr.bein",  desc:"Balanse + glute." },

  // ── LEGGER (12) ──
  { id:"l1",  name:"Stående leggcurl (calf raise)", eng:"Standing Calf Raise",         group:"legger", equipment:"maskin",    level:"begynner",  sets:"4 x 12",    desc:"Stå på platå - hev hælene." },
  { id:"l2",  name:"Sittende calf raise",           eng:"Seated Calf Raise",           group:"legger", equipment:"maskin",    level:"begynner",  sets:"4 x 15",    desc:"Sittende - solearis-fokus." },
  { id:"l3",  name:"Donkey calf raise",             eng:"Donkey Calf Raise",           group:"legger", equipment:"maskin",    level:"middels",   sets:"3 x 15",    desc:"Bøyd over - strekk på gastrocnemius." },
  { id:"l4",  name:"Single-leg calf raise",         eng:"Single-Leg Calf Raise",       group:"legger", equipment:"kroppsvekt",level:"begynner",  sets:"3 x 15 pr.bein", desc:"En leg av gangen - korrigér ubalanse." },
  { id:"l5",  name:"Calf raise på beinpress",       eng:"Leg Press Calf Raise",        group:"legger", equipment:"maskin",    level:"begynner",  sets:"3 x 15",    desc:"Føtter på platta - press med tærne." },
  { id:"l6",  name:"Smith calf raise",              eng:"Smith Calf Raise",            group:"legger", equipment:"smith",     level:"begynner",  sets:"3 x 15",    desc:"Smith - sikker stand med tung vekt." },
  { id:"l7",  name:"Bonded calf raise",             eng:"Banded Calf Raise",           group:"legger", equipment:"bånd",      level:"begynner",  sets:"3 x 20",    desc:"Bånd om kne - sitt og hev." },
  { id:"l8",  name:"Tibialis raise",                eng:"Tibialis Raise",              group:"legger", equipment:"kroppsvekt",level:"begynner",  sets:"3 x 15",    desc:"Stå mot vegg - hev tærne." },
  { id:"l9",  name:"Anti-shin raise",               eng:"Toes-Up Raise",               group:"legger", equipment:"manual",    level:"begynner",  sets:"3 x 15",    desc:"Sittende - manual på føttene - hev tærne." },
  { id:"l10", name:"Box jump",                      eng:"Box Jump",                    group:"legger", equipment:"kroppsvekt",level:"middels",   sets:"4 x 8",     desc:"Eksplosivt hopp på boks." },
  { id:"l11", name:"Pogo hopp",                     eng:"Pogo Jump",                   group:"legger", equipment:"kroppsvekt",level:"begynner",  sets:"3 x 20",    desc:"Stive bein - hopp som pinne." },
  { id:"l12", name:"Calf walk farmer",              eng:"Tip-Toe Walk",                group:"legger", equipment:"manual",    level:"middels",   sets:"3 x 30 m",  desc:"Gå på tå med manualer." },

  // ── MAGE / KJERNE (30) ──
  { id:"m1",  name:"Plankehold",                    eng:"Plank",                       group:"mage",   equipment:"kroppsvekt",level:"begynner",  sets:"3 x 45 s",  desc:"Isometrisk - hold rett linje." },
  { id:"m2",  name:"Side plank",                    eng:"Side Plank",                  group:"mage",   equipment:"kroppsvekt",level:"begynner",  sets:"3 x 30 s pr.side", desc:"Sideligg - skrå mage." },
  { id:"m3",  name:"Plank med rotasjon",            eng:"Plank Rotation",              group:"mage",   equipment:"kroppsvekt",level:"middels",   sets:"3 x 10",    desc:"Veksle mellom planke og side." },
  { id:"m4",  name:"Hanging leg raise",             eng:"Hanging Leg Raise",           group:"mage",   equipment:"kroppsvekt",level:"middels",   sets:"3 x 10",    desc:"Heng i stang - hev rake bein." },
  { id:"m5",  name:"Hanging knee raise",            eng:"Hanging Knee Raise",          group:"mage",   equipment:"kroppsvekt",level:"begynner",  sets:"3 x 12",    desc:"Heng - bøy knær opp." },
  { id:"m6",  name:"Toes to bar",                   eng:"Toes-to-Bar",                 group:"mage",   equipment:"kroppsvekt",level:"erfaren",   sets:"3 x 8",     desc:"Heng - berør stang med tærne." },
  { id:"m7",  name:"Ab wheel rollout",              eng:"Ab Wheel Rollout",            group:"mage",   equipment:"hjul",      level:"middels",   sets:"3 x 10",    desc:"Rull hjul fram fra knestående." },
  { id:"m8",  name:"Cable crunch",                  eng:"Cable Crunch",                group:"mage",   equipment:"kabel",     level:"begynner",  sets:"3 x 15",    desc:"Knestående - krøll mot lår." },
  { id:"m9",  name:"Knestående cable woodchopper",  eng:"Cable Woodchopper",           group:"mage",   equipment:"kabel",     level:"middels",   sets:"3 x 12 pr.side", desc:"Diagonal pull - skrå mage." },
  { id:"m10", name:"Russian twist",                 eng:"Russian Twist",               group:"mage",   equipment:"manual",    level:"begynner",  sets:"3 x 20",    desc:"Sittende - vri side til side." },
  { id:"m11", name:"Bicycle crunch",                eng:"Bicycle Crunch",              group:"mage",   equipment:"kroppsvekt",level:"begynner",  sets:"3 x 20",    desc:"Albue mot motsatt kne." },
  { id:"m12", name:"V-up",                          eng:"V-Up",                        group:"mage",   equipment:"kroppsvekt",level:"middels",   sets:"3 x 12",    desc:"Ligg - hev bein og overkropp til V." },
  { id:"m13", name:"Hollow hold",                   eng:"Hollow Hold",                 group:"mage",   equipment:"kroppsvekt",level:"middels",   sets:"3 x 30 s",  desc:"Ligg - kraftig kjernekontraksjon." },
  { id:"m14", name:"Dead bug",                      eng:"Dead Bug",                    group:"mage",   equipment:"kroppsvekt",level:"begynner",  sets:"3 x 12",    desc:"Ligg - motsatt arm og bein." },
  { id:"m15", name:"Bird dog",                      eng:"Bird Dog",                    group:"mage",   equipment:"kroppsvekt",level:"begynner",  sets:"3 x 10",    desc:"Firfotet - strekk motsatt." },
  { id:"m16", name:"Mountain climber",              eng:"Mountain Climber",            group:"mage",   equipment:"kroppsvekt",level:"begynner",  sets:"3 x 30 s",  desc:"Pushup-pos - veksle knær mot bryst." },
  { id:"m17", name:"Tuck up",                       eng:"Tuck Up",                     group:"mage",   equipment:"kroppsvekt",level:"middels",   sets:"3 x 12",    desc:"Ligg - bøy alt sammen til ball." },
  { id:"m18", name:"L-sit",                         eng:"L-Sit",                       group:"mage",   equipment:"kroppsvekt",level:"erfaren",   sets:"3 x 15 s",  desc:"Hold L-stilling - sterke mage." },
  { id:"m19", name:"Dragon flag",                   eng:"Dragon Flag",                 group:"mage",   equipment:"kroppsvekt",level:"erfaren",   sets:"3 x 5",     desc:"Senk strake kropp - super hardt." },
  { id:"m20", name:"Pallof press",                  eng:"Pallof Press",                group:"mage",   equipment:"kabel",     level:"begynner",  sets:"3 x 12",    desc:"Press kabel rett ut - antirotasjon." },
  { id:"m21", name:"Suitcase carry",                eng:"Suitcase Carry",              group:"mage",   equipment:"manual",    level:"begynner",  sets:"3 x 30 m",  desc:"Bær en tung manual - antiflex." },
  { id:"m22", name:"Single-arm farmer walk",        eng:"Single-Arm Farmer Walk",      group:"mage",   equipment:"manual",    level:"middels",   sets:"3 x 30 m",  desc:"En manual - kjerne stabilisering." },
  { id:"m23", name:"Decline situp",                 eng:"Decline Sit-up",              group:"mage",   equipment:"kroppsvekt",level:"middels",   sets:"3 x 15",    desc:"Føttene oppe - dypere ROM." },
  { id:"m24", name:"Stang situp",                   eng:"Weighted Sit-up",             group:"mage",   equipment:"manual",    level:"middels",   sets:"3 x 12",    desc:"Hold manual mot brystet." },
  { id:"m25", name:"Reverse crunch",                eng:"Reverse Crunch",              group:"mage",   equipment:"kroppsvekt",level:"begynner",  sets:"3 x 15",    desc:"Ligg - rull baken opp mot hode." },
  { id:"m26", name:"Stang twist",                   eng:"Landmine Twist",              group:"mage",   equipment:"stang",     level:"middels",   sets:"3 x 10",    desc:"Stang i landmine - twist side." },
  { id:"m27", name:"Plate halo",                    eng:"Plate Halo",                  group:"mage",   equipment:"manual",    level:"begynner",  sets:"3 x 10",    desc:"Skive rundt hodet - kjerne og skulder." },
  { id:"m28", name:"Around-the-world",              eng:"Around the World",            group:"mage",   equipment:"manual",    level:"begynner",  sets:"3 x 12",    desc:"Sirkel med skive rundt kroppen." },
  { id:"m29", name:"Cable rotation",                eng:"Standing Cable Rotation",     group:"mage",   equipment:"kabel",     level:"middels",   sets:"3 x 12",    desc:"Stå - roter mot kabel." },
  { id:"m30", name:"Stir-the-pot",                  eng:"Stir the Pot",                group:"mage",   equipment:"kroppsvekt",level:"middels",   sets:"3 x 10 pr.side", desc:"Planke på ball - rør store sirkler." },

  // ── HELKROPP / FUNKSJONELL (18) ──
  { id:"hk1", name:"Clean (henging)",               eng:"Hang Clean",                  group:"helkropp",equipment:"stang",    level:"erfaren",   sets:"4 x 3",     desc:"Eksplosiv stang fra hofte til skuldre." },
  { id:"hk2", name:"Clean & jerk",                  eng:"Clean & Jerk",                group:"helkropp",equipment:"stang",    level:"erfaren",   sets:"4 x 2",     desc:"Olympisk - clean + push over hode." },
  { id:"hk3", name:"Snatch",                        eng:"Snatch",                      group:"helkropp",equipment:"stang",    level:"erfaren",   sets:"4 x 2",     desc:"Olympisk - en bevegelse fra gulv over hode." },
  { id:"hk4", name:"Power clean",                   eng:"Power Clean",                 group:"helkropp",equipment:"stang",    level:"erfaren",   sets:"4 x 3",     desc:"Stang fra gulv til skuldre uten dyp catch." },
  { id:"hk5", name:"Thruster",                      eng:"Thruster",                    group:"helkropp",equipment:"stang",    level:"middels",   sets:"4 x 8",     desc:"Front squat → press over hode." },
  { id:"hk6", name:"Manual thruster",               eng:"Dumbbell Thruster",           group:"helkropp",equipment:"manual",   level:"middels",   sets:"3 x 10",    desc:"Manual variant av thruster." },
  { id:"hk7", name:"Wallball",                      eng:"Wall Ball",                   group:"helkropp",equipment:"manual",   level:"begynner",  sets:"3 x 15",    desc:"Squat + kast ball mot mål." },
  { id:"hk8", name:"Burpee",                        eng:"Burpee",                      group:"helkropp",equipment:"kroppsvekt",level:"begynner", sets:"3 x 15",    desc:"Pushup + hopp - hele kroppen." },
  { id:"hk9", name:"Burpee box jump",               eng:"Burpee Box Jump",             group:"helkropp",equipment:"kroppsvekt",level:"middels",  sets:"3 x 10",    desc:"Burpee fulgt av box jump." },
  { id:"hk10",name:"Kettlebell swing",              eng:"KB Swing",                    group:"helkropp",equipment:"kettlebell",level:"middels",  sets:"3 x 20",    desc:"Hofte-eksplosivitet - kettlebell." },
  { id:"hk11",name:"KB clean",                      eng:"Kettlebell Clean",            group:"helkropp",equipment:"kettlebell",level:"middels",  sets:"3 x 8",     desc:"KB fra gulv til skulder-rack." },
  { id:"hk12",name:"KB snatch",                     eng:"Kettlebell Snatch",           group:"helkropp",equipment:"kettlebell",level:"erfaren",  sets:"3 x 5 pr.side",desc:"KB fra gulv til over hode." },
  { id:"hk13",name:"Sandbag clean",                 eng:"Sandbag Clean",               group:"helkropp",equipment:"manual",   level:"middels",   sets:"3 x 6",     desc:"Sandsekk fra gulv til skulder." },
  { id:"hk14",name:"Bear crawl",                    eng:"Bear Crawl",                  group:"helkropp",equipment:"kroppsvekt",level:"begynner", sets:"3 x 20 m",  desc:"Krabb fram - hender og føtter." },
  { id:"hk15",name:"Turkish get-up",                eng:"Turkish Get-up",              group:"helkropp",equipment:"kettlebell",level:"middels",  sets:"3 x 5 pr.side",desc:"Komplett fra ligg til stå med KB over hode." },
  { id:"hk16",name:"Battle ropes",                  eng:"Battle Ropes",                group:"helkropp",equipment:"manual",   level:"middels",   sets:"4 x 30 s",  desc:"Slå tau - kondisjon og overkropp." },
  { id:"hk17",name:"Tire flip",                     eng:"Tire Flip",                   group:"helkropp",equipment:"manual",   level:"erfaren",   sets:"3 x 5",     desc:"Snu stort dekk - bakkjeden." },
  { id:"hk18",name:"Sled pull",                     eng:"Sled Pull",                   group:"helkropp",equipment:"maskin",   level:"middels",   sets:"4 x 20 m",  desc:"Trekk slede - bakover eller fram." }
];
